apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todolist
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 5050
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: 3000
